---
vm_name: brug
app_name: '{{ vm_name }}'

git_branch: master
vm_os: ubuntu/trusty64
environments:
  - development
  - production
  - staging
package_bundles:
  - curl
  - graphics
  - qt
packages:
  - curl
  - libcurl3
  - libcurl3-gnutls
  - libcurl4-openssl-dev
  - imagemagick
  - qt5-default
  - libqt5webkit5-dev
manual_ruby_version: 
server_name: localhost
rails_version: 3
ruby_install: rbenv
ruby_version: 2.0.0-p645
environment_file: '/{{ vm_name }}/.envrc'
databases:
  - mysql
background_jobs:
  - delayed_job
postgresql_orm: none
mysql_orm: activerecord
mongodb_orm: none
redis_orm: none
mongodb_db_name: myapp
mysql_db_name: '{{ app_name }}'
mysql_db_user: vagrant
mysql_db_password: qw12
postgresql_db_name: myapp
postgresql_db_user: vagrant
postgresql_db_password: 
postgresql_extensions:
delayed_job_command: rake jobs:work
sunspot_solr_command: rake sunspot:solr:start
sidekiq_command: sidekiq
resque_command: rake resque:work
server_type: nginx_unicorn
git_url: git@github.com:/vasvitaly/belarus-ruby-on-rails.git
delayed_job_app_name: '{{ app_name }}-delayed_job'
sunspot_solr_app_name: '{{ app_name }}-sunspot_solr'

app_name: '{{ vm_name }}'
path: '/{{ app_name }}'
user_name: '{{ "vagrant" if target == "virtualbox" else vm_name }}'
group_name: '{{ user_name }}'

releases_path: '{{ path }}/releases'
shared_path: '{{ path }}/shared'

user_home_path: '/home/{{ user_name }}'

ssl_certificate_path: /etc/nginx/ssl/{{ server_name }}.crt
ssl_certificate_key_path: /etc/nginx/ssl/{{ server_name }}.key

server_path: "{{ path }}/current"
app_path: '{{ path if target == "virtualbox" else server_path }}'
app_public_path: "{{ app_path }}/public"
app_config_path: '{{ app_path if target == "virtualbox" else shared_path }}/config'
# app_config_path: "{{ app_path }}/config"
app_temp_path: "{{ app_path }}/tmp"
app_logs_path: "{{ app_path }}/log"


unicorn_sock_path: "/tmp/unicorn.{{ rails_env }}.sock"
unicorn_config_path: "{{ app_config_path }}/unicorn.{{ rails_env }}.rb"
unicorn_pid_path: "{{ app_temp_path }}/unicorn.{{ rails_env }}.pid"
unicorn_stderr_path: "{{ app_logs_path }}/unicorn.err.log"
unicorn_stdout_path: "{{ app_logs_path }}/unicorn.log"

puma_bind_path: "unix://{{ app_temp_path }}/sockets/puma.{{ rails_env }}.sock"
puma_config_path: "{{ app_config_path }}/puma.{{ rails_env }}.rb"
puma_pidfile_path: "{{ app_temp_path }}/pids/puma.{{ rails_env }}.pid"
puma_stderr_redirect_path: "{{ app_logs_path }}/puma.{{ rails_env }}.err.log"
puma_stdout_redirect_path: "{{ app_logs_path }}/puma.{{ rails_env }}.log"

ruby_user_name: '{{ "root" if ruby_install == "package" else user_name }}'

use_apt_proxy: false
