---
- name: Update apt cache
  apt: update_cache=yes

- name: Install apt dependencies
  apt: name={{ item }}
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - nodejs
    - python-pip
    - python-dev
    - htop
    - git

- name: Install additional packages
  apt: name={{ item }}
  with_items: packages
  when: packages

- name: Create application group
  group: name={{ group_name }}

- name: Create application user
  user: name={{ user_name }} group={{ group_name }} shell=/bin/bash home={{ user_home_path }}

- name: Make sure user`s .ssh folder exists
  file: 
    path: '/home/{{ user_name }}/.ssh'
    state: directory
    owner: '{{ user_name }}'
    group: '{{ group_name }}'
    mode: 0700


- name: Copy id_rsa key for github to the user`s ssh folder
  copy: 
    src: '../../../../ssh_keys/id_rsa'
    dest: '/home/{{ user_name }}/.ssh/id_rsa'
    owner: '{{ user_name }}'
    group: '{{ group_name }}'
    mode: 0600

- name: Copy id_rsa.pub for github to the user`s ssh folder
  copy: 
    src: '../../../../ssh_keys/id_rsa.pub'
    dest: '/home/{{ user_name }}/.ssh/id_rsa.pub'
    owner: '{{ user_name }}'
    group: '{{ group_name }}'
    mode: "u=rw,g=r,o=r"

- name: Setup script to read application environment
  template: src=read_environment.sh.j2 dest=/etc/profile.d/read_environment.sh

- name: Create profile.d directory
  file: path={{ profile_d_path }} state=directory owner={{ user_name }} group={{ group_name }}

- name: Create ~/.bash_profile which loads all from ~/profile.d
  template: src=bash_profile.j2 dest={{ user_home_path }}/.bash_profile owner={{ user_name }} group={{ group_name }}
