---
- include_vars: ../../unicorn/defaults/main.yml
- include_vars: ../../delayed_job/defaults/main.yml

- set_fact: this_release_path={{ releases_path }}/{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}

- debug: msg='New release path {{ this_release_path }}'

- name: Create new release dir
  file: path={{ this_release_path }} state=directory

- name: Update code
  git: repo={{ git_url }} dest={{ this_release_path }} version={{ git_branch }} accept_hostkey=yes
  register: git
  notify:
    - restart delayed_job

- debug: msg='Updated repo from {{ git.before }} to {{ git.after }}'

- name: Delete log directory
  file: path={{ this_release_path }}/log state=absent

- name: Symlink shared files
  file: src={{ shared_path }}/{{ item }} dest={{ this_release_path }}/{{ item }} state=link force=yes
  with_items:
    - config/database.yml
    - config/social_config.yml
    - config/unicorn.{{ rails_env }}.rb
    - log
    - tmp
    - vendor/bundle
    - public/system
    - public/ckeditor_assets

- name: Install bundle
  command: /bin/bash -l -c 'bundle install --deployment --without="development test"' chdir={{ this_release_path }}

- name: Set site
  command: /bin/bash -l -c 'ruby set_site.rb {{app_name}} ln' chdir={{ this_release_path }}

- name: Precompile assets
  command: /bin/bash -l -c 'bundle exec rake assets:precompile' chdir={{ this_release_path }}
  environment:
    RAILS_ENV: '{{ rails_env }}'

- name: Migrate database
  command: /bin/bash -l -c 'bundle exec rake db:migrate' chdir={{ this_release_path }}
  environment:
    RAILS_ENV: '{{ rails_env }}'

- name: Symlink new release
  file: src={{ this_release_path }} dest={{ app_path }} state=link force=yes

- name: Restart unicorn
  command: sudo {{ server_restart_command }}

- name: Cleanup
  shell: "ls -1t {{ releases_path }}|tail -n +{{ keep_releases + 1 }}|xargs rm -rf"
  args:
    chdir: '{{ releases_path }}'

- name: Update solr cache
  command: /bin/bash -l -c 'bundle exec rake sunspot:reindex' chdir={{ app_path }}
