---
- include: remote.yml
  when: target == 'server'

- name: Restore initial DB dump for virtualbox
  command: /bin/bash -l -c 'mysql -u{{ mysql_db_user }} -p{{ mysql_db_password }} --default-character-set=utf8 {{ mysql_db_name }} < db/{{ app_name }}_dump.sql' chdir={{ app_path }}
  sudo_user: '{{ user_name }}'
  ignore_errors: yes
  when: target == 'virtualbox'

- name: Restore initial DB dump for server
  command: /bin/bash -l -c 'mysql -u{{ mysql_db_user }} -p{{ mysql_db_password }} --default-character-set=utf8 {{ mysql_db_name }} < {{ shared_path }}/tmp/{{ app_name }}_dump.sql'
  sudo_user: '{{ user_name }}'
  ignore_errors: yes
  when: target == 'server'
