site_name: 'bjug'
host: 'belarusjug.org'
info_mail: 'info@belarusjug.org'
notifier:
  default:
    from: 'Белорусское сообщество Java <info@belarusjug.org>'
    to: 'info@belarusjug.org'
xml:
  title: 'Белорусское сообщество Java'
  description: 'Новости сообщества Java в Беларуси'
devise:
  mailer_sender: 'Белорусское сообщество Java <no-reply@belarusjug.org>'
cookie_store:
  key: '_BelarusJava_session'